def operation(act_num_1, act_num_2, act_oper):
    if act_oper == '+':
        return act_num_1 + act_num_2
    elif act_oper == '-':
        return act_num_1 - act_num_2
    elif act_oper == '*':
        return act_num_1 * act_num_2
    elif act_oper == '/':
        return act_num_1 / act_num_2
